#!/usr/bin/env bash

# The name of polybar bar which houses the main playerctl module and the control modules.
PARENT_BAR="i3"
PARENT_BAR_PID=$(pgrep -a "polybar" | grep "$PARENT_BAR" | cut -d" " -f1)

# Format of the information displayed
# Eg. {{ artist }} - {{ album }} - {{ title }}
# See more attributes here: https://github.com/altdesktop/playerctl/#printing-properties-and-metadata
FORMAT="{{ title }} - {{ artist }}"

# Sends $2 as message to all polybar PIDs that are part of $1
update_hooks() {
		polybar-msg action "#playerctl-play-pause.hook.$1" 1>/dev/null 2>&1
}

PLAYERCTL_STATUS=$(playerctl status 2>/dev/null)
EXIT_CODE=$?

if [ "$EXIT_CODE" -eq 0 ]; then
	STATUS=$PLAYERCTL_STATUS
else
	STATUS="No player is running"
fi

if [ "$STATUS" = "Stopped" ]; then
	echo "No music is playing"
elif [ "$STATUS" = "Paused" ]; then
	update_hooks 0
	playerctl metadata --format "$FORMAT"
elif [ "$STATUS" = "No player is running" ]; then
	echo "$STATUS"
else
	update_hooks 1
	playerctl metadata --format "$FORMAT"
fi
